# Frontend Service Build Configuration
FROM node:22-alpine

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
RUN npm i -g serve
COPY . .
RUN npm run build

EXPOSE 8080

LABEL org.opencontainers.image.source=https://github.com/CS4366/SIREN
LABEL org.opencontainers.image.title="SIREN Frontend Service"

CMD ["serve","-p","8080","-s", "dist"]