# Build Stage: Build the assets using Node
FROM node:22-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Final Stage: Use a minimal Nginx image to serve the static files
FROM nginx:alpine

# Remove default Nginx static files and copy your build output
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

LABEL org.opencontainers.image.source="https://github.com/CS4366/SIREN"
LABEL org.opencontainers.image.title="SIREN Frontend Service"

CMD ["nginx", "-g", "daemon off;"]