# Developer Docker Compose
services:
  message-queue:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
