# NOAA Service Build Configuration
FROM golang:1.23.4

WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-noaa-service

LABEL org.opencontainers.image.source=https://github.com/CS4366/SIREN
LABEL org.opencontainers.image.title="SIREN NOAA Service"

CMD ["/docker-noaa-service"]