# NOAA Service Build Configuration
#Build Stage
FROM golang:1.23.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o docker-noaa-service .

# Final Stage: Use a minimal base image
FROM scratch

# Need to copy the CA certificates from the builder stage
# This is necessary for HTTPS requests to work in the final image
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /app/docker-noaa-service /docker-noaa-service

LABEL org.opencontainers.image.source=https://github.com/CS4366/SIREN
LABEL org.opencontainers.image.title="SIREN NOAA Service"

CMD ["/docker-noaa-service"]