# Tracking Service Build Configuration
FROM golang:1.23.4

WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-tracking-service

LABEL org.opencontainers.image.source=https://github.com/CS4366/SIREN
LABEL org.opencontainers.image.title="SIREN Tracking Service"

CMD ["/docker-tracking-service"]