# Build Stage: Use the full Golang image to build the binary
FROM golang:1.24.2 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o docker-tracking-service .

# Final Stage: Use a minimal base image
FROM scratch

# Need to copy the CA certificates from the builder stage
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /app/docker-tracking-service /docker-tracking-service

# Add image metadata labels
LABEL org.opencontainers.image.source="https://github.com/CS4366/SIREN"
LABEL org.opencontainers.image.title="SIREN Tracking Service"

EXPOSE 6091

# Specify the binary as the entrypoint
CMD ["/docker-tracking-service"]