# Build Phase
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production Phase
FROM node:22-alpine as prod
WORKDIR /app
COPY --from=build /app/package*.json ./
COPY --from=build /app/dist ./dist

RUN npm install --production

LABEL org.opencontainers.image.source=https://github.com/CS4366/SIREN
LABEL org.opencontainers.image.title="SIREN Push Service"

EXPOSE 4000
CMD ["node", "dist/push.js"]