# Stage 1: Build the application
FROM node:22-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

RUN npm prune --production

# Stage 2: Create the final, lean runtime image
FROM node:22-alpine
WORKDIR /app

# Copy necessary files from the builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 4000

LABEL org.opencontainers.image.source="https://github.com/CS4366/SIREN"
LABEL org.opencontainers.image.title="SIREN API Service"

# Start the application
CMD ["node", "dist/api.js"]
