# --- Stage 1: Build Stage ---
FROM node:22-alpine AS builder
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install
RUN npm prune --production


# Copy the full app and build it
COPY . .
RUN npm run build

# --- Stage 2: Production Stage ---
FROM node:22-alpine AS final
WORKDIR /app

# Copy only production node_modules and built app from builder stage
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/nws_ugc.lmdb ./nws_ugc.lmdb
COPY --from=builder /app/nws_ugc.lmdb-lock ./nws_ugc.lmdb-lock

# Labels
LABEL org.opencontainers.image.source="https://github.com/CS4366/SIREN"
LABEL org.opencontainers.image.title="SIREN API Service"

# Expose API port
EXPOSE 3030

# Start the application
CMD ["node", "dist/api.js"]
