name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.app.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          [
            {
              name: "NOAA Service",
              path: "services/noaa-service",
              build-type: "go",
            },
            {
              name: "Tracking Service",
              path: "services/tracking-service",
              build-type: "go",
            },
            {
              name: "Frontend Service",
              path: "services/frontend-service",
              build-type: "node",
            },
            {
              name: "API Service",
              path: "services/api-service",
              build-type: "node",
            },
            {
              name: "Push Service",
              path: "services/push-service",
              build-type: "node",
            },
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: changes
        name: Check for Folder Changes
        with:
          filters: |
            src:
              - '.github/workflows/build.yml'
              - '${{ matrix.app.path }}/**'

      - name: Set up Go
        if: steps.changes.outputs.src == 'true' && ${{ matrix.app.build-type }} == 'go'
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.4"

      - name: Set up Node.js
        if: steps.changes.outputs.src == 'true' && ${{ matrix.app.build-type }} == 'node'
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Build
        if: steps.changes.outputs.src == 'true'
        run: |
          cd ${{ matrix.app.path }}
          if [ "${{ matrix.app.build-type }}" == "go" ]; then
            go mod tidy
            go build
          else
            npm install
            npm run build
          fi
